from __future__ import annotations

import re
from pathlib import Path


def _title(transcript: str, slug: str) -> str:
    for line in transcript.splitlines():
        if line.lower().startswith("title:"):
            return line.split(":", 1)[1].strip()
    return slug.replace("-", " ").title()


def _bullets(transcript: str) -> list[str]:
    bullets = []
    for line in transcript.splitlines():
        s = line.strip()
        if re.match(r"(?i)^step\s+\w+:", s) or s.lower().startswith("takeaway:"):
            bullets.append(s)
        elif s.lower().startswith("common mistake:"):
            bullets.append(s)
    if not bullets:
        bullets = [ln.strip() for ln in transcript.splitlines() if ln.strip()][:5]
    return bullets


def generate_lab(transcript_path: Path, out_dir: Path, slug: str | None = None) -> Path:
    text = transcript_path.read_text(encoding="utf-8")
    slug = slug or transcript_path.parent.name
    title = _title(text, slug)
    bullets = _bullets(text)
    lab = out_dir / slug
    lab.mkdir(parents=True, exist_ok=True)

    readme = [
        f"# Lab: {title}",
        "",
        f"Generated by clip2lab from `{transcript_path}`.",
        "",
        "## Learning objectives",
        "",
    ]
    for b in bullets:
        readme.append(f"- {b}")
    readme += [
        "",
        "## Lab steps",
        "",
        "1. Skim the transcript in `source/transcript.txt`.",
        "2. Complete the quiz in `quiz.md`.",
        "3. Optional: wire the skill stub into your agent toolkit.",
        "",
    ]
    (lab / "README.md").write_text("\n".join(readme) + "\n", encoding="utf-8")

    quiz_lines = ["# Quiz", "", f"Topic: {title}", ""]
    for i, b in enumerate(bullets[:3], 1):
        quiz_lines += [f"## Q{i}", "", f"Explain or critique: {b}", "", "Answer:", "", "---", ""]
    (lab / "quiz.md").write_text("\n".join(quiz_lines) + "\n", encoding="utf-8")

    skill = f"""# Skill stub: {slug}

## Purpose
Help an agent teach or quiz the lab **{title}**.

## Tools (suggested)
- `get_lab_readme`
- `quiz_learner`

## Source
Generated from transcript; review before production use.
"""
    (lab / "SKILL.md").write_text(skill, encoding="utf-8")
    source = lab / "source"
    source.mkdir(exist_ok=True)
    (source / "transcript.txt").write_text(text, encoding="utf-8")
    return lab
